# base/kustomization.yaml
resources:
- ./citizendocs/charts/postgresql/templates/secrets.yaml
- ./citizendocs/charts/postgresql/templates/primary/svc-headless.yaml
- ./citizendocs/charts/postgresql/templates/primary/statefulset.yaml
- ./citizendocs/charts/postgresql/templates/primary/svc.yaml
- ./citizendocs/templates/service-backend.yaml
- ./citizendocs/templates/service-frontend.yaml
- ./citizendocs/templates/deployment-backend.yaml
- ./citizendocs/templates/deployment-frontend.yaml
- ./citizendocs/templates/route-frontend.yaml