apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  host: {{ .Values.route.frontend.host }}
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
  port:
    targetPort: 80
