---
# Source: citizendocs/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: citizendocs-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.9.13
    app.kubernetes.io/instance: citizendocs
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "dWZ3ZVVXU3JyNQ=="
  password: "bXlzZWNyZXRwYXNzd29yZA=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
