apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-helm-deploy-run-
spec:
  pipelineRef:
    name: clone-build-push-helm-deploy
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/PacktPublishing/Mastering-OpenShift/
  - name: imageUrl
    value: quay.io/<your namespace>/citizendocs-backend

  