# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: citizendocs-backend
    path: replica_count.yaml


